apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: application
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings
  tasks:
    ## Fetch repo from Git
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "https://github.com/andcip/quarkus-helm-tekton-example.git"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: master
        - name: sslVerify
          value: "false"
      workspaces:
        - name: output
          workspace: shared-workspace
    ## Build with maven
    - name: maven-package
      taskRef:
        name: maven
        kind: ClusterTask
      runAfter:
        - fetch-repository
      params:
        - name: GOALS
          value:
            - '-B'
            - '-DskipTests'
            - '-Dmaven.javadoc.skip=true'
            - clean
            - package
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    ## Run Unit tests
    - name: maven-unit-tests
      taskRef:
        name: maven
        kind: ClusterTask
      runAfter:
        - maven-package
      params:
        - name: GOALS
          value:
            - '-B'
            - test
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings

    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - maven-unit-tests
      params:
        - name: DOCKERFILE
          value: "src/main/docker/Dockerfile.jvm"
        - name: IMAGE
          value: "instance-quay-quay-registry.apps.lab01.gpslab.club/acipriani/application:1.0"
        - name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: helm-install-upgrade
      taskRef:
        name: helm-upgrade-from-source
        kind: ClusterTask
      runAfter:
        - build-image
      params:
        - name: charts_dir
          value: "./helm"
        - name: release_version
          value: master
        - name: release_name
          value: "application"
        - name: values_file
          value: "values.yaml"
        - name: release_namespace
          value: andcip-workshop
        - name: helm_image
          value: "instance-quay-quay-registry.apps.lab01.gpslab.club/acipriani/helm"
      workspaces:
        - name: source
          workspace: shared-workspace