apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: application
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: gitlab-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: application
  template:
    ref: application

